=== api-evangelist/amazon-outposts/json-schema/openapi-outpost-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-outposts/refs/heads/main/json-schema/openapi-outpost-schema.json",
  "title": "Outpost",
  "description": "Information about an Outpost.",
  "type": "object",
  "properties": {
    "OutpostId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutpostId"
        },
        {
          "description": " The ID of the Outpost. "
        }
      ]
    },
    "OwnerId": {
      "$ref": "#/components/schemas/OwnerId"
    },
    "OutpostArn": {
      "$ref": "#/components/schemas/OutpostArn"
    },
    "SiteId": {
      "$ref": "#/components/schemas/SiteId"
    },
    "Name": {
      "$ref": "#/components/schemas/OutpostName"
    },
    "Description": {
      "$ref": "#/components/schemas/OutpostDescription"
    },
    "LifeCycleStatus": {
      "$ref": "#/components/schemas/LifeCycleStatus"
    },
    "AvailabilityZone": {
      "$ref": "#/components/schemas/AvailabilityZone"
    },
    "AvailabilityZoneId": {
      "$ref": "#/components/schemas/AvailabilityZoneId"
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagMap"
        },
        {
          "description": "The Outpost tags."
        }
      ]
    },
    "SiteArn": {
      "$ref": "#/components/schemas/SiteArn"
    },
    "SupportedHardwareType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SupportedHardwareType"
        },
        {
          "description": " The hardware type. "
        }
      ]
    }
  }
}

=== api-evangelist/amazon-outposts/examples/openapi-outpost-example.json
{
  "OutpostId": "resource-abc123",
  "OwnerId": "example-ref",
  "OutpostArn": "example-ref",
  "SiteId": "example-ref",
  "Name": "example-ref",
  "Description": "example-ref",
  "LifeCycleStatus": "example-ref",
  "AvailabilityZone": "example-ref",
  "AvailabilityZoneId": "example-ref",
  "Tags": "example-string",
  "SiteArn": "example-ref",
  "SupportedHardwareType": "standard"
}
